---
prometheus:
  pushgateway:
    enabled: false
  server:
    persistentVolume:
      enabled: true
      storageClass: "ebs-sc"
      accessModes:
        - ReadWriteOnce
      size: 50Gi
  alertmanager:
    persistentVolume:
      enabled: true
      storageClass: "ebs-sc"
      accessModes:
        - ReadWriteOnce
      size: 10Gi

