---
controller:
  enableSnippets: true
  image:
    repository: private-registry.nginx.com/nginx-ic-nap-v5/nginx-plus-ingress
    tag: 3.6.1
    pullPolicy: Always
  nginxplus: true
  nginxStatus:
    allowCidrs: 0.0.0.0/0
    port: 9000
  readyStatus:
    initialDelaySeconds: 30
  serviceAccount:
    imagePullSecretName: regcred 
prometheus:
  create: true
