{
 "title": "NginxaaS Dashboard",
 "templating": {
  "list": [
   { "name": "resourceGroup", "label": "Resource Group", "query": "YOUR RESOURCE GROUP NAME" },
   { "name": "region", "label": "Region", "query": "YOUR AZURE REGION NAME" },
   { "name": "nginxResource", "label": "NGINX Resource", "query": "YOUR NGINXaaS NAME" },
   { "name": "vm1", "label": "VM 1", "query": "YOUR VM-1 NAME" },
   { "name": "vm2", "label": "VM 2", "query": "YOUR VM-2 NAME" }
  ]
 },
 "panels": [
  { "title": "NGINXaaS-Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NCU Stats",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginxaas statistics",
      "dimensionFilters": [],
      "metricName": "ncu.provisioned",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginxaas statistics",
      "dimensionFilters": [],
      "metricName极": "ncu.requested",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINXaaS Statistics",
      "dimensionFilters": [],
      "metricName": "ncu.consumed",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "NGINX connections statistics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.accepted",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.dropped",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.active",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.idle",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.current",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "NGINX worker statistics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.accepted",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.dropped",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.active",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.idle",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.http.request.total",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.http.request.current",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Upstream Statistics",
      "dimensionFilters": [
       {
        "dimension": "upstream",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.upstream.peers.response.time",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "HTTP Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.upstream.peers.status.2xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.upstream.peers.status.3xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.upstream.peers.status.4xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.upstream.peers.status.5xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     },
     "ref极": "D"
    }
   ]
  },
  {
   "title": "NGINX connections statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.cpu",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.bytes_rcvd",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.bytes_sent",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.current",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "SSL Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX SSL Statistics",
      "dimensionFilters": [
       {
        "dimension": "server_zone",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.ssl.handshakes",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX SSL Statistics",
      "dimensionFilters": [
       {
        "dimension": "server_zone",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.ssl.reuses",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX SSL Statistics",
      "dimensionFilters": [
       {
        "dimension": "server_zone",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.ssl.handshakes_timeout",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Cache Statistics",
      "dimensionFilters": [
       { "dimension": "cache_zone", "filters": [ "image_cache" ], "operator": "eq" }
      ],
      "metricName": "plus.cache.hit.ratio",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Upstream Statistics",
      "dimensionFilters": [
       {
        "dimension": "upstream",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.upstream.peers.health_checks.checks",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Upstream Statistics",
      "dimensionFilters": [
       {
        "dimension": "upstream",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.upstream.peers.health_checks.unhealthy",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "nginx.nginxplus/nginxdeployments",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "$nginxResource"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  { "title": "Virtual Machines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Inbound Flows VM1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Inbound Flows - ${vm1}",
      "dimensionFilters": [],
      "metricName": "Inbound Flows",
      "metricNamespace": "Microsoft.Compute/virtualMachines",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "${vm1}"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Inbound Flows VM2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Inbound Flows - ${vm2}",
      "dimensionFilters": [],
      "metricName": "Inbound Flows",
      "metricNamespace": "Microsoft.Compute/virtualMachines",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "${vm2}"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "System Metrics VM1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Disk Read - ${vm1}",
      "dimensionFilters": [],
      "metricName": "Disk Read Bytes",
      "metricNamespace": "Microsoft.Compute/virtualMachines",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "${vm1}"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Disk Write - ${vm1}",
      "dimensionFilters": [],
      "metricName": "Disk Write Bytes",
      "metricNamespace": "Microsoft.Compute/virtualMachines",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "${vm1}"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "CPU % - ${vm1}",
      "dimensionFilters": [],
      "metricName": "Percentage CPU",
      "metricNamespace": "Microsoft.Compute/virtualMachines",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "${vm1}"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Available Memory - ${vm1}",
      "dimensionFilters": [],
      "metricName": "Available Memory Bytes",
      "metricNamespace": "Microsoft.Compute/virtualMachines",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "${vm1}"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "System Metrics VM2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Disk Read - ${vm2}",
      "dimensionFilters": [],
      "metricName": "Disk Read Bytes",
      "metricNamespace": "Microsoft.Compute/virtualMachines",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "${vm2}"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Disk Write - ${vm2}",
      "dimensionFilters": [],
      "metricName": "Disk Write Bytes",
      "metricNamespace": "Microsoft.Compute/virtualMachines",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "${vm2}"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "CPU % - ${vm2}",
      "dimensionFilters": [],
      "metricName": "Percentage CPU",
      "metricNamespace": "Microsoft.Compute/virtualMachines",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "${vm2}"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Available Memory - ${vm2}",
      "dimensionFilters": [],
      "metricName": "Available Memory Bytes",
      "metricNamespace": "Microsoft.Compute/virtualMachines",
      "region": "$region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "$region",
        "resourceGroup": "$resourceGroup",
        "resourceName": "${vm2}"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  }
 ]
}