name: " Deploy NGINX NIC/NAP-V5 in Azure"
on:
  push:
    branches: az-apply-nic-napv5
env:
    TF_VAR_project_prefix : ${{ vars.project_prefix }}
    TF_VAR_azure_region: ${{ vars.azure_region }}
    TF_VAR_azure_credentials : ${{ secrets.azure_credentials }}
    TF_VAR_resource_group_name : ${{ vars.project_prefix }}-rg
    TF_VAR_storage_account_name : ${{ vars.storage_account_name }}
    TF_VAR_container_name : ${{ vars.storage_account_name }}-container

jobs:
  terraform_blob:
    name: "Deploy Blob Storage"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./azure/blob
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Azure Credentials
        uses: azure/login@v2
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform (Backend)
        run: |
          terraform init

      - name: Terraform Plan
        run: terraform plan -no-color -input=false -out=tfplan

      - name: Check for Changes
        id: check_changes
        run: |
          if grep -q "No changes." <(terraform show -no-color tfplan); then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/az-apply-nic-napv5' && steps.check_changes.outputs.has_changes == 'true'
        run: terraform apply -auto-approve tfplan


  terraform_infra:
      name: "Deploy Azure Infra"
      runs-on: ubuntu-latest
      needs:  terraform_blob
      permissions:
        contents: read
      defaults:
        run:
          working-directory: ./azure/infra

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Configure Azure Credentials
          uses: azure/login@v2
          with:
            creds: ${{ secrets.azure_credentials }}

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Initialize Terraform (Azure Backend)
          run: |
            terraform init \
            -backend-config="resource_group_name=${{ vars.project_prefix }}-rg" \
            -backend-config="storage_account_name=${{ vars.storage_account_name}}" \
            -backend-config="container_name=${{ vars.storage_account_name }}-container"

        - name: Terraform Plan
          if: github.event_name == 'pull_request' || github.event_name == 'push'
          run: |
            terraform plan -no-color -input=false -out=tfplan
            terraform show -no-color tfplan > plan.txt

        - name: Check Changes
          id: check_changes
          run: |
            if grep -q "No changes." plan.txt; then
              echo "has_changes=false" >> $GITHUB_OUTPUT
            else
              echo "has_changes=true" >> $GITHUB_OUTPUT
            fi

        - name: Terraform Apply
          if: github.event_name == 'push' && github.ref == 'refs/heads/az-apply-nic-napv5' && steps.check_changes.outputs.has_changes == 'true'
          run: terraform apply -auto-approve tfplan

  terraform_aks:
    name: "Deploy AKS"
    runs-on: ubuntu-latest
    needs: terraform_infra
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./azure/aks
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Azure Credentials
        uses: azure/login@v2
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform (Azure Backend)
        run: |
          terraform init \
          -backend-config="resource_group_name=${{ vars.project_prefix }}-rg" \
          -backend-config="storage_account_name=${{ vars.storage_account_name }}" \
          -backend-config="container_name=${{ vars.storage_account_name }}-container"

      - name: Terraform Plan
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        run: |
          terraform plan -no-color -input=false  -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Check Changes
        id: check_changes
        run: |
          if grep -q "No changes." plan.txt; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/az-apply-nic-napv5' && steps.check_changes.outputs.has_changes == 'true'
        run: terraform apply -auto-approve tfplan

  terraform_nap:
    name: "Deploy NGINC NIC/App Protect"
    runs-on: ubuntu-latest
    needs: terraform_aks
    defaults:
      run:
        working-directory: ./azure/nap
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Azure Credentials
        uses: azure/login@v2
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform (Azure Backend)
        run: |
          terraform init \
          -backend-config="resource_group_name=${{ vars.project_prefix }}-rg" \
          -backend-config="storage_account_name=${{ vars.storage_account_name }}" \
          -backend-config="container_name=${{ vars.storage_account_name }}-container"

      - name: Terraform Plan
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        run: |
          terraform plan -no-color -input=false -lock=false -out=tfplan \
            -var="workspace_path=${{ env.WORKSPACE_PATH }}" \
            -var="nginx_jwt=${{ secrets.NGINX_JWT }}" \
            -var="nginx_pwd=none"
          terraform show -no-color tfplan > plan.txt
        env:
           WORKSPACE_PATH: "./azure/nap"

      - name: Check Changes
        id: check_changes
        run: |
          if grep -q "No changes." plan.txt; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/az-apply-nic-napv5' && steps.check_changes.outputs.has_changes == 'true'
        run: terraform apply -auto-approve -lock=false tfplan

  terraform_policy:
    name: "Deploy NGINX Policy"
    runs-on: ubuntu-latest
    needs: terraform_nap
    defaults:
      run:
       working-directory: ./azure/policy
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure Azure Credentials
      uses: azure/login@v2
      with:
        creds: ${{ secrets.azure_credentials }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize Terraform (Azure Backend)
      run: |
        terraform init \
        -backend-config="resource_group_name=${{ vars.project_prefix }}-rg" \
        -backend-config="storage_account_name=${{ vars.storage_account_name }}" \
        -backend-config="container_name=${{ vars.storage_account_name }}-container"
      working-directory: ./azure/aks

    - name: Print AKS Terraform Outputs
      run: terraform output
      working-directory: ./azure/aks

    - name: Fetch AKS Cluster Name and Region
      run: |
        echo "RESOURCE_GROUP_NAME=${{ vars.project_prefix }}-rg" >> $GITHUB_ENV
        echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> $GITHUB_ENV
      working-directory: ./azure/aks

    - name: Configure kubectl for Azure
      run: |
        az aks get-credentials --resource-group $RESOURCE_GROUP_NAME --name $CLUSTER_NAME

    - name: Verify kubectl connectivity
      run: kubectl get nodes -n nginx-ingress

    - name: Install Docker and Docker Compose
      run: |
        sudo apt-get update -y
        sudo apt-get remove -y containerd containerd.io
        sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update -y
        sudo apt-get install docker-ce docker-ce-cli containerd.io -y
        sudo service docker start
        sudo usermod -aG docker $USER

        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Create Certificates Directory for Docker
      run: |
        sudo mkdir -p /etc/docker/certs.d/private-registry.nginx.com

    - name: Create NGINX Repository Certificate for Docker
      run: echo "${{ secrets.NGINX_REPO_CRT }}" | sudo tee /etc/docker/certs.d/private-registry.nginx.com/client.cert > /dev/null

    - name: Create NGINX Repository Key for Docker
      run: echo "${{ secrets.NGINX_REPO_KEY }}" | sudo tee /etc/docker/certs.d/private-registry.nginx.com/client.key > /dev/null

    - name: Create Certificates Directory for NGINX
      run: |
        sudo mkdir -p /etc/ssl/nginx

    - name: Save NGINX Repository Certificate for NGINX
      run: echo "${{ secrets.NGINX_REPO_CRT }}" | sudo tee /etc/ssl/nginx/nginx-repo.crt > /dev/null

    - name: Save NGINX Repository Key for NGINX
      run: echo "${{ secrets.NGINX_REPO_KEY }}" | sudo tee /etc/ssl/nginx/nginx-repo.key > /dev/null

    - name: Build Docker Image
      run: |
        docker build --no-cache \
          --secret id=nginx-crt,src=/etc/ssl/nginx/nginx-repo.crt \
          --secret id=nginx-key,src=/etc/ssl/nginx/nginx-repo.key \
          -t waf-compiler-5.4.0:custom .

    - name: Ensure correct permissions for nap/charts directory
      run: |
        echo ${{ github.workspace }}/azure
        sudo chown -R $USER:$USER ${{ github.workspace }}/azure
        sudo chmod -R 777 ${{ github.workspace }}/azure

    - name: Run Docker Container as Root
      run: |
        docker run --rm \
            -v ${{ github.workspace }}:/workspace \
              waf-compiler-5.4.0:custom \
            -p /workspace/azure/policy/policy.json -o /workspace/azure/policy/compiled_policy.tgz

    - name: Fix permissions for compiled files
      run: |
        sudo chown -R $USER:$USER ${{ github.workspace }}/azure/policy
        chmod 644 ${{ github.workspace }}/azure/policy/compiled_policy.tgz
        ls -lh ${{ github.workspace }}/azure/policy


    - name: Copy Compiled Policy to NGINX Ingress Controller
      run: |
        NGINX_POD=$(kubectl get pods -n nginx-ingress -l app.kubernetes.io/name=nginx-ingress -o jsonpath='{.items[0].metadata.name}')
        if [ -z "$NGINX_POD" ]; then
          echo "Error: NGINX Ingress Controller pod not found!"
          exit 1
        fi
        kubectl cp ${{ github.workspace }}/azure/policy/compiled_policy.tgz $NGINX_POD:/etc/app_protect/bundles/compiled_policy.tgz -n nginx-ingress

    - name: Initialize Terraform (Azure Backend)
      run: |
        terraform init \
        -backend-config="resource_group_name=${{ vars.project_prefix }}-rg" \
        -backend-config="storage_account_name=${{ vars.storage_account_name }}" \
        -backend-config="container_name=${{ vars.storage_account_name }}-container"

    - name: Terraform Plan
      run: |
        terraform plan -no-color -input=false -out=tfplan
        terraform show -no-color tfplan > plan.txt

    - name: Check Changes
      id: check_changes
      run: |
        if grep -q "No changes." plan.txt; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/az-apply-nic-napv5' && steps.check_changes.outputs.has_changes == 'true'
      run: terraform apply -auto-approve tfplan

  terraform_arcadia:
    name: "Deploy Arcadia WebApp"
    runs-on: ubuntu-latest
    needs: terraform_policy
    defaults:
      run:
        working-directory: ./azure/arcadia
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Azure Credentials
        uses: azure/login@v2
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform (Azure Backend)
        run: |
          terraform init \
          -backend-config="resource_group_name=${{ vars.project_prefix }}-rg" \
          -backend-config="storage_account_name=${{ vars.storage_account_name }}" \
          -backend-config="container_name=${{ vars.storage_account_name }}-container"

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        run: |
          terraform plan -no-color -input=false -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Check Changes
        id: check_changes
        run: |
          if grep -q "No changes." plan.txt; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/az-apply-nic-napv5' && steps.check_changes.outputs.has_changes == 'true'
        run: terraform apply -auto-approve tfplan

      - name: Get Terraform Outputs
        run: |
          terraform output -json > outputs.json
          EXTERNAL_NAME=$(jq -r '.external_name.value // empty' outputs.json)

          if [ -z "$EXTERNAL_NAME" ]; then
            echo "::warning::No external_name output found"
          else
            echo "external_name=$EXTERNAL_NAME" >> $GITHUB_ENV
            echo "NGINX Ingress External Name: $EXTERNAL_NAME"
          fi
