name: Apply NGINXaaS WAF Deployment with Grafana

on:
  push:
    branches: [nginxaas-apply]
  workflow_dispatch:
env:
  TF_VAR_grafana_admin_object_ids: ${{ secrets.grafana_admin_object_ids }}
  TF_VAR_subscription_id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
  TF_VAR_admin_ip: ${{ secrets.ADMIN_IP }}
  TF_VAR_project_prefix: ${{ vars.project_prefix }}
  TF_VAR_resource_group_name: ${{ vars.resource_group_name }}
  TF_VAR_azure_region: ${{ vars.azure_region }}
  TF_VAR_ssh_public_key: ${{ secrets.ssh_public_key }}

jobs:
  terraform:
    name: 'Deploy NGINXaaS WAF & Grafana'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./azure/nginxaas
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Check for Changes
        id: check_changes
        run: |
          if grep -q "No changes." <(terraform show -no-color tfplan); then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Install Azure Grafana CLI extension
        run: az extension add --name amg --upgrade --yes

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/nginxaas-apply' && steps.check_changes.outputs.has_changes == 'true'
        run: terraform apply -input=false -auto-approve tfplan